# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/presentation/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(752, 457)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_general)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_general)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lvSources = QtWidgets.QListWidget(self.tab_general)
        self.lvSources.setObjectName("lvSources")
        self.horizontalLayout_3.addWidget(self.lvSources)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnAddSource = QtWidgets.QPushButton(self.tab_general)
        self.btnAddSource.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnAddSource.setBaseSize(QtCore.QSize(0, 0))
        self.btnAddSource.setObjectName("btnAddSource")
        self.verticalLayout_2.addWidget(self.btnAddSource)
        self.btnRemoveSource = QtWidgets.QPushButton(self.tab_general)
        self.btnRemoveSource.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnRemoveSource.setBaseSize(QtCore.QSize(0, 0))
        self.btnRemoveSource.setObjectName("btnRemoveSource")
        self.verticalLayout_2.addWidget(self.btnRemoveSource)
        self.btEditSource = QtWidgets.QPushButton(self.tab_general)
        self.btEditSource.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btEditSource.setBaseSize(QtCore.QSize(0, 0))
        self.btEditSource.setObjectName("btEditSource")
        self.verticalLayout_2.addWidget(self.btEditSource)
        self.btnWeb = QtWidgets.QPushButton(self.tab_general)
        self.btnWeb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnWeb.setObjectName("btnWeb")
        self.verticalLayout_2.addWidget(self.btnWeb)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cbNSFW = QtWidgets.QCheckBox(self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbNSFW.sizePolicy().hasHeightForWidth())
        self.cbNSFW.setSizePolicy(sizePolicy)
        self.cbNSFW.setText("")
        self.cbNSFW.setObjectName("cbNSFW")
        self.gridLayout.addWidget(self.cbNSFW, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_general)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.teInterval = QtWidgets.QTimeEdit(self.tab_general)
        self.teInterval.setObjectName("teInterval")
        self.gridLayout.addWidget(self.teInterval, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_wallpaper = QtWidgets.QWidget()
        self.tab_wallpaper.setObjectName("tab_wallpaper")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_wallpaper)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cb_enable_prettification = QtWidgets.QCheckBox(self.tab_wallpaper)
        self.cb_enable_prettification.setObjectName("cb_enable_prettification")
        self.verticalLayout_4.addWidget(self.cb_enable_prettification)
        self.gb_prettification = QtWidgets.QGroupBox(self.tab_wallpaper)
        self.gb_prettification.setObjectName("gb_prettification")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_prettification)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.gb_prettification)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.dsb_threshold = QtWidgets.QDoubleSpinBox(self.gb_prettification)
        self.dsb_threshold.setMinimumSize(QtCore.QSize(80, 0))
        self.dsb_threshold.setObjectName("dsb_threshold")
        self.horizontalLayout_4.addWidget(self.dsb_threshold)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.gb_prettification)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.sb_width = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_width.sizePolicy().hasHeightForWidth())
        self.sb_width.setSizePolicy(sizePolicy)
        self.sb_width.setMinimumSize(QtCore.QSize(80, 0))
        self.sb_width.setMaximum(20000)
        self.sb_width.setProperty("value", 1920)
        self.sb_width.setObjectName("sb_width")
        self.gridLayout_2.addWidget(self.sb_width, 0, 1, 1, 1)
        self.sb_height = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_height.sizePolicy().hasHeightForWidth())
        self.sb_height.setSizePolicy(sizePolicy)
        self.sb_height.setMinimumSize(QtCore.QSize(80, 0))
        self.sb_height.setMaximum(20000)
        self.sb_height.setProperty("value", 1080)
        self.sb_height.setObjectName("sb_height")
        self.gridLayout_2.addWidget(self.sb_height, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.cb_repeat_backround = QtWidgets.QCheckBox(self.gb_prettification)
        self.cb_repeat_backround.setObjectName("cb_repeat_backround")
        self.verticalLayout.addWidget(self.cb_repeat_backround)
        self.gb_repeat_settings = QtWidgets.QGroupBox(self.gb_prettification)
        self.gb_repeat_settings.setObjectName("gb_repeat_settings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_repeat_settings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_blur_background = QtWidgets.QCheckBox(self.gb_repeat_settings)
        self.cb_blur_background.setObjectName("cb_blur_background")
        self.verticalLayout_5.addWidget(self.cb_blur_background)
        self.gb_blur_settings = QtWidgets.QGroupBox(self.gb_repeat_settings)
        self.gb_blur_settings.setObjectName("gb_blur_settings")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_blur_settings)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gb_blur_settings)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dsb_amount = QtWidgets.QDoubleSpinBox(self.gb_blur_settings)
        self.dsb_amount.setMinimumSize(QtCore.QSize(80, 0))
        self.dsb_amount.setObjectName("dsb_amount")
        self.horizontalLayout_2.addWidget(self.dsb_amount)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.cb_blend_edges = QtWidgets.QCheckBox(self.gb_blur_settings)
        self.cb_blend_edges.setObjectName("cb_blend_edges")
        self.verticalLayout_6.addWidget(self.cb_blend_edges)
        self.gb_blend_settings = QtWidgets.QGroupBox(self.gb_blur_settings)
        self.gb_blend_settings.setObjectName("gb_blend_settings")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gb_blend_settings)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.gb_blend_settings)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.dsb_blend_ratio = QtWidgets.QDoubleSpinBox(self.gb_blend_settings)
        self.dsb_blend_ratio.setMinimumSize(QtCore.QSize(80, 0))
        self.dsb_blend_ratio.setObjectName("dsb_blend_ratio")
        self.gridLayout_5.addWidget(self.dsb_blend_ratio, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.gb_blend_settings)
        self.verticalLayout_5.addWidget(self.gb_blur_settings)
        self.verticalLayout.addWidget(self.gb_repeat_settings)
        self.verticalLayout_4.addWidget(self.gb_prettification)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab_wallpaper, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOk = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOk.sizePolicy().hasHeightForWidth())
        self.btnOk.setSizePolicy(sizePolicy)
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        SettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.label.setText(_translate("SettingsWindow", "Wallpaper Sources:"))
        self.btnAddSource.setText(_translate("SettingsWindow", "+"))
        self.btnRemoveSource.setText(_translate("SettingsWindow", "-"))
        self.btEditSource.setText(_translate("SettingsWindow", "edit"))
        self.btnWeb.setText(_translate("SettingsWindow", "web"))
        self.label_3.setText(_translate("SettingsWindow", "Include NSFW:"))
        self.label_2.setText(_translate("SettingsWindow", "Interval (hh:mm):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("SettingsWindow", "General"))
        self.cb_enable_prettification.setToolTip(_translate("SettingsWindow", "<html><head/><body><p>If prettification is\n"
"                                          enabled, a new wallpaper will be generated where the source image will be put\n"
"                                          into its center. Unless repeat image in background is checked, the background\n"
"                                          will be filled with the median edge color of the central image.</p><p><span\n"
"                                          style=\" font-weight:600;\">Be aware that this option will cost\n"
"                                          some performance while the wallpaper gets generated and it will slow down\n"
"                                          wallpaper changing.</span></p></body></html>\n"
"                                      "))
        self.cb_enable_prettification.setText(_translate("SettingsWindow", "Enable prettification"))
        self.gb_prettification.setTitle(_translate("SettingsWindow", "Prettification settings"))
        self.label_8.setText(_translate("SettingsWindow", "Prettification threshold:"))
        self.dsb_threshold.setToolTip(_translate("SettingsWindow", "<html><head/><body><p>Prettification\n"
"                                                              is only applied if the source image ratio and definded\n"
"                                                              width/height ratio difference exceedes this threshold.\n"
"                                                              Lower values mean the ratio has to be more similar, bigger\n"
"                                                              values mean the ratios can deviate more.</p></body></html>\n"
"                                                          "))
        self.groupBox_3.setTitle(_translate("SettingsWindow", "Wallpaper size"))
        self.label_7.setText(_translate("SettingsWindow", "Height:"))
        self.label_6.setText(_translate("SettingsWindow", "Width:"))
        self.sb_width.setToolTip(_translate("SettingsWindow", "The resulting width of the generated wallpaper.\n"
"                                                              "))
        self.sb_height.setToolTip(_translate("SettingsWindow", "The resulting height of the generated wallpaper.\n"
"                                                              "))
        self.cb_repeat_backround.setToolTip(_translate("SettingsWindow", "<html><head/><body><p>If repeat image\n"
"                                                      in background is checked, the source image will be repeated in the\n"
"                                                      background instead of the median color. A gaussian blur can also\n"
"                                                      be applied only to the images in the background if checked.</p></body></html>\n"
"                                                  "))
        self.cb_repeat_backround.setText(_translate("SettingsWindow", "Repeat image in background"))
        self.gb_repeat_settings.setTitle(_translate("SettingsWindow", "Repeat settings"))
        self.cb_blur_background.setToolTip(_translate("SettingsWindow", "<html><head/><body><p>If\n"
"                                                                  blur background is selected, a gaussian blur is\n"
"                                                                  applied to the background before the central image is\n"
"                                                                  composited in.</p></body></html>\n"
"                                                              "))
        self.cb_blur_background.setText(_translate("SettingsWindow", "Blur background"))
        self.gb_blur_settings.setTitle(_translate("SettingsWindow", "Blur settings"))
        self.label_4.setText(_translate("SettingsWindow", "Amount:"))
        self.dsb_amount.setToolTip(_translate("SettingsWindow", "The amount of blur that should\n"
"                                                                                      be applied.\n"
"                                                                                  "))
        self.cb_blend_edges.setToolTip(_translate("SettingsWindow", "<html><head/><body><p>If\n"
"                                                                              blend edges is checked, the edges of the\n"
"                                                                              central image are blended with the\n"
"                                                                              background to get a smoother transition.</p></body></html>\n"
"                                                                          "))
        self.cb_blend_edges.setText(_translate("SettingsWindow", "Blend edges with background"))
        self.gb_blend_settings.setTitle(_translate("SettingsWindow", "Blend Settings"))
        self.label_5.setText(_translate("SettingsWindow", "Blend ratio:"))
        self.dsb_blend_ratio.setToolTip(_translate("SettingsWindow", "how many percent of the\n"
"                                                                                          central image should be\n"
"                                                                                          blurred. (0=0%, 1=100%)\n"
"                                                                                      "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wallpaper), _translate("SettingsWindow", "Wallpaper"))
        self.btnCancel.setText(_translate("SettingsWindow", "cancel"))
        self.btnOk.setText(_translate("SettingsWindow", "ok"))

