# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Multiplatform build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check-out repository
      uses: actions/checkout@v4.1.1

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: '3.10'
        # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
        cache: 'pip'
        # Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.
        cache-dependency-path: |
            requirements.txt
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executables from Python projects
      uses: Nuitka/Nuitka-Action@v1.1
      with:
        nuitka-version: main
        script-name: 'wpcg/wpcg.py'
        standalone: true
        onefile: true
        disable-console: true
        enable-plugins: pyside6
        company-name: 'github.com/JakobPer'
        product-name: 'wpcg'
        file-description: 'wpcg'
        file-version: '0.0.1'
        windows-icon-from-ico: 'wpcg/icons/icon.ico'

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
         name: wpcg_${{ runner.os }}
         path: | # match what's created for the 3 OSes
            build/*.exe
            build/*.bin
            build/*.app/**/*
